package government.data;
// Generated Dec 12, 2015 7:57:01 PM by Hibernate Tools 4.3.1



/**
 * Citizen generated by hbm2java
 */
public class Citizen  implements java.io.Serializable {


     private Integer id;
     private Province province;
     private String name;
     private int age;

    public Citizen() {
    }
    public Citizen(Province province, String name, int age) {
       this.province = province;
       this.name = name;
       this.age = age;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    @Override
    public String toString()
    {
        return "Citizen{" + "province=" + province + ", name=" + name + ", age=" + age + '}';
    }



}


