package government.data;
// Generated Dec 12, 2015 7:57:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
public class Province  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set citizens = new HashSet(0);

    public Province() {
    }

	
    public Province(String name) {
        this.name = name;
    }
    public Province(String name, Set citizens) {
       this.name = name;
       this.citizens = citizens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCitizens() {
        return this.citizens;
    }
    
    public void setCitizens(Set citizens) {
        this.citizens = citizens;
    }

    @Override
    public String toString()
    {
        return "Province{" + "name=" + name +'}';
    }




}


